spring:
    profiles:
        active: prod

server:
    port: 5000

app:
    datasource:
        jdbc-url: jdbc:postgresql://suisendb.cql93dwxjfib.us-east-2.rds.amazonaws.com:5432/suisendb
        username: mrsteph3
        password: Ilm3dJaM123
        pool-size: 30