server:
    servlet:
        context-path: /api/v1

app:
    datasource:
        jdbc-url: jdbc:postgresql://localhost:5432/suisendb
        username: postgres
        password: password
        pool-size: 30

server.error.include-message: always

spring:
    flyway:
        baseline-on-migrate: true
